### ISSUE TITLE
Bump version in CMakeLists

### ISSUE THREAD

**Issue by drbild** [xaptum/ecdaa#130]
The version in `CMakeLists.txt` was not bumped from 0.10.1 when the v0.10.2 release was cut. My suggestion is to bump to v0.10.3 and release again as v0.10.3.

**Comment by zanebeckwith** [comment]
Fixed.

Sorry, I was doing this quickly at the end of the day Friday, and overlooked the version in the cmake.

I also added a new `ecdaa` deb that contains the CLI tool.
