### ISSUE TITLE
Apt packages and future distro support

### ISSUE THREAD

**Issue by preisacm** [xaptum/ecdaa#141]
The link to the Ubuntu repo (http://dl.bintray.com/xaptum/deb) is not public accessible.
Can you please provide link for the Ubuntu releases (deb https://xaptum.jfrog.io/ui/native/debian bionic main) in the README.md

Do you plan to provide packages and support for recent and future Debian/Ubuntu releases?

Best regards,
Michael Preisach

**Comment by zanebeckwith** [comment]
> The link to the Ubuntu repo (http://dl.bintray.com/xaptum/deb) is not public accessible

The repo has moved to https://xaptum.jfrog.io/artifactory/debian.

> Can you please provide link for the Ubuntu releases (deb https://xaptum.jfrog.io/ui/native/debian bionic main) in the README.md

The README was updated a couple of months ago with the new URL (as above). Is that what you mean? Or are you still having trouble with the instructions given in the README?

> Do you plan to provide packages and support for recent and future Debian/Ubuntu releases?

Support for Ubuntu Focal (the current LTS) is on my TODO list, I just need to find the time to do it! And as for future releases, yes, the plan is to maintain support, though you may need to ping me to get me to do it!

**Comment by drbild** [comment]
I think the confusion is that I forgot to remove the old (bintray) Ubuntu section when I updated the readme and combined the Debian and Ubuntu sections.

**Comment by zanebeckwith** [comment]
> I forgot to remove the old (bintray) Ubuntu section when I updated the readme and combined the Debian and Ubuntu sections

Ah, I see. I didn't even scroll down far enough to notice that!

I'll remove that (now outdated) section now

Thanks David!
