### ISSUE TITLE
Ensure we're not using patented algorithms in AMCL

### ISSUE THREAD

**Issue by zanebeckwith** [xaptum/ecdaa#3]
Comments in AMCL's build setup indicate that some curve point multiplication algorithm(s) they use is/maybe patented.

I don't think we're using that, but make sure we're not.

**Comment by zanebeckwith** [comment]
An earlier CMake option that toggled patented algorithms (and which, I believe, was disabled by default) appears to no longer be available.

The only locations where "patent" appears in their source code, currently, relate to the `GLV` and `GS_G2` algorithms (which are point multiplication, I believe?). These are (again, currently) commented out.

So, right now, we appear to not be using any patented algorithms in AMCL.

**Comment by drbild** [comment]
This isn't really an `ecdaa` issue anyway, right?   It's up to the person building `amcl` to decide whether or not to include the patented algorithms (if `amcl` even still exposes those).  `ecdaa` just links against an existing `amcl` binary; it's not setting those options.

**Comment by zanebeckwith** [comment]
Yea, good point. I was worried about the Apache-licensing concerns for us, but you're right.

Closing
